-- MySQL Script generated by MySQL Workbench
-- Qua 23 Set 2015 10:31:03 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tcc` ;

-- -----------------------------------------------------
-- Table `tcc`.`base_acoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`base_acoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `palavra` VARCHAR(20) NOT NULL,
  `sugestao` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`base_sufixo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`base_sufixo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sufixo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`desconsidera_verbos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`desconsidera_verbos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `verbo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`reducao_plural`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`reducao_plural` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `remover_sufixo` VARCHAR(3) NOT NULL,
  `tamanho_minimo` INT NOT NULL,
  `substituir_sufixo` VARCHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`reducao_feminino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`reducao_feminino` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `remover_sufixo` VARCHAR(4) NOT NULL,
  `tamanho_minimo` INT NOT NULL,
  `substituir_sufixo` VARCHAR(4) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`reducao_aumentativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`reducao_aumentativo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `remover_sufixo` VARCHAR(10) NOT NULL,
  `tamanho_minimo` INT NOT NULL,
  `substituir_sufixo` VARCHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`reducao_nominal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`reducao_nominal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `remover_sufixo` VARCHAR(10) NOT NULL,
  `tamanho_minimo` INT NOT NULL,
  `substituir_sufixo` VARCHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`reducao_verbal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`reducao_verbal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `remover_sufixo` VARCHAR(3) NOT NULL,
  `tamanho_minimo` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`remocao_vogal_tematica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`remocao_vogal_tematica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `remover_sufixo` VARCHAR(1) NOT NULL,
  `tamanho_minimo` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `tcc`.`base_acoes`
-- -----------------------------------------------------
START TRANSACTION;
USE `tcc`;
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (1, 'inserir', 1);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (2, 'incluir', 1);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (3, 'informar', 1);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (4, 'adicionar', 1);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (5, 'pesquisar', 5);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (6, 'consultar', 5);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (7, 'buscar', 5);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (8, 'procurar', 5);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (9, 'localizar', 5);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (10, 'editar', 10);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (11, 'alterar', 10);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (12, 'modificar', 10);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (13, 'excluir', 13);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (14, 'eliminar', 13);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (15, 'deletar', 13);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (16, 'apagar', 13);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (17, 'remover', 13);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (18, 'exibir', 18);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (19, 'mostrar', 18);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (20, 'apresentar', 18);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (21, 'visualizar', 21);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (22, 'ver', 21);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (23, 'cadastrar', 23);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (24, 'criar', 23);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (25, 'requisitar', 25);
INSERT INTO `tcc`.`base_acoes` (`id`, `palavra`, `sugestao`) VALUES (26, 'solicitar', 25);

COMMIT;


-- -----------------------------------------------------
-- Data for table `tcc`.`base_sufixo`
-- -----------------------------------------------------
START TRANSACTION;
USE `tcc`;
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (1, 'ente');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (2, 'entes');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (3, 'enta');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (4, 'entas');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (5, 'or');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (6, 'ores');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (7, 'ora');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (8, 'oras');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (9, 'eiro');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (10, 'eiros');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (11, 'eira');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (12, 'eiras');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (13, 'ário');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (14, 'ários');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (15, 'ária');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (16, 'árias');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (17, 'es');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (18, 'eses');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (19, 'esa');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (20, 'esas');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (21, 'eus');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (22, 'euses');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (23, 'eusa');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (24, 'eusas');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (25, 'ia');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (26, 'ias');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (27, 'ante');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (28, 'antes');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (29, 'ador');
INSERT INTO `tcc`.`base_sufixo` (`id`, `sufixo`) VALUES (30, 'adores');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tcc`.`desconsidera_verbos`
-- -----------------------------------------------------
START TRANSACTION;
USE `tcc`;
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (1, 'haver');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (2, 'fazer');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (3, 'ser');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (4, 'viver');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (5, 'encontrar');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (6, 'parecer');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (7, 'estar');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (8, 'continuar');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (9, 'ficar');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (10, 'permanecer');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (11, 'andar');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (12, 'tomar');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (13, 'virar');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (14, 'tornar');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (15, 'acabar');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (16, 'ter');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (17, 'vir');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (18, 'conter');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (19, 'deter');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (20, 'manter');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (21, 'obter');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (22, 'provir');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (23, 'intervir');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (24, 'convir');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (25, 'encontrar');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (26, 'possuir');
INSERT INTO `tcc`.`desconsidera_verbos` (`id`, `verbo`) VALUES (27, 'pertencer');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tcc`.`reducao_plural`
-- -----------------------------------------------------
START TRANSACTION;
USE `tcc`;
INSERT INTO `tcc`.`reducao_plural` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (1, 'ns', 1, 'm');
INSERT INTO `tcc`.`reducao_plural` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (2, 'ões', 3, 'ão');
INSERT INTO `tcc`.`reducao_plural` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (3, 'ães', 1, 'ão');
INSERT INTO `tcc`.`reducao_plural` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (4, 'ais', 1, 'al');
INSERT INTO `tcc`.`reducao_plural` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (5, 'éis', 2, 'el');
INSERT INTO `tcc`.`reducao_plural` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (6, 'eis', 2, 'el');
INSERT INTO `tcc`.`reducao_plural` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (7, 'óis', 2, 'ol');
INSERT INTO `tcc`.`reducao_plural` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (8, 'is', 2, 'il');
INSERT INTO `tcc`.`reducao_plural` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (9, 'les', 3, 'l');
INSERT INTO `tcc`.`reducao_plural` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (10, 'res', 3, 'r');
INSERT INTO `tcc`.`reducao_plural` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (11, 's', 1, '');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tcc`.`reducao_feminino`
-- -----------------------------------------------------
START TRANSACTION;
USE `tcc`;
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (1, 'ona', 3, 'ão');
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (2, 'ã', 2, 'ão');
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (3, 'ora', 3, 'or');
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (4, 'na', 4, 'no');
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (5, 'inha', 3, 'inho');
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (6, 'esa', 3, 'ês');
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (7, 'osa', 3, 'oso');
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (8, 'íaca', 3, 'íaco');
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (9, 'ica', 3, 'ico');
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (10, 'ada', 2, 'ado');
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (11, 'ida', 3, 'ido');
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (12, 'ída', 3, 'ido');
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (13, 'ima', 3, 'imo');
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (14, 'iva', 3, 'ivo');
INSERT INTO `tcc`.`reducao_feminino` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (15, 'eira', 3, 'eiro');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tcc`.`reducao_aumentativo`
-- -----------------------------------------------------
START TRANSACTION;
USE `tcc`;
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (1, 'díssimo', 5, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (2, 'abilíssimo', 5, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (3, 'íssimo', 3, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (4, 'érrimo', 4, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (5, 'zinho', 2, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (6, 'quinho', 4, 'c');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (7, 'uinho', 4, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (8, 'adinho', 3, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (9, 'inho', 3, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (10, 'alhão', 4, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (11, 'uça', 4, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (12, 'aço', 4, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (13, 'adão', 4, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (14, 'ázio', 3, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (15, 'arraz', 4, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (16, 'arra', 3, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (17, 'zão', 2, '');
INSERT INTO `tcc`.`reducao_aumentativo` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (18, 'ão', 3, '');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tcc`.`reducao_nominal`
-- -----------------------------------------------------
START TRANSACTION;
USE `tcc`;
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (1, 'encialista', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (2, 'alista', 5, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (3, 'agem', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (4, 'iamento', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (5, 'amento', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (6, 'imento', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (7, 'alizado', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (8, 'atizado', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (9, 'izado', 5, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (10, 'ativo', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (11, 'tivo', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (12, 'ivo', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (13, 'ado', 2, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (14, 'ido', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (15, 'ador', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (16, 'edor', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (17, 'idor', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (18, 'atória', 5, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (19, 'or', 2, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (20, 'abilidade', 5, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (21, 'icionista', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (22, 'cionista', 5, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (23, 'ional', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (24, 'ência', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (25, 'ância', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (26, 'edouro', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (27, 'queiro', 3, 'c');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (28, 'eiro', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (29, 'oso', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (30, 'alizaç', 5, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (31, 'ismo', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (32, 'izaç', 5, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (33, 'aç', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (34, 'iç', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (35, 'ário', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (36, 'ério', 6, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (37, 'ês', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (38, 'eza', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (39, 'ez', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (40, 'esco', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (41, 'ante', 2, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (42, 'ástico', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (43, 'ático', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (44, 'ico', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (45, 'ividade', 5, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (46, 'idade', 5, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (47, 'oria', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (48, 'encial', 5, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (49, 'ista', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (50, 'quice', 4, 'c');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (51, 'ice', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (52, 'íaco', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (53, 'ente', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (54, 'inal', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (55, 'ano', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (56, 'ável', 2, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (57, 'ível', 5, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (58, 'ura', 4, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (59, 'ual', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (60, 'ial', 3, '');
INSERT INTO `tcc`.`reducao_nominal` (`id`, `remover_sufixo`, `tamanho_minimo`, `substituir_sufixo`) VALUES (61, 'al', 4, '');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tcc`.`reducao_verbal`
-- -----------------------------------------------------
START TRANSACTION;
USE `tcc`;
INSERT INTO `tcc`.`reducao_verbal` (`id`, `remover_sufixo`, `tamanho_minimo`) VALUES (1, 'ear', 4);
INSERT INTO `tcc`.`reducao_verbal` (`id`, `remover_sufixo`, `tamanho_minimo`) VALUES (2, 'ar', 2);
INSERT INTO `tcc`.`reducao_verbal` (`id`, `remover_sufixo`, `tamanho_minimo`) VALUES (3, 'er', 2);
INSERT INTO `tcc`.`reducao_verbal` (`id`, `remover_sufixo`, `tamanho_minimo`) VALUES (4, 'ir', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `tcc`.`remocao_vogal_tematica`
-- -----------------------------------------------------
START TRANSACTION;
USE `tcc`;
INSERT INTO `tcc`.`remocao_vogal_tematica` (`id`, `remover_sufixo`, `tamanho_minimo`) VALUES (1, 'a', 3);
INSERT INTO `tcc`.`remocao_vogal_tematica` (`id`, `remover_sufixo`, `tamanho_minimo`) VALUES (2, 'e', 3);
INSERT INTO `tcc`.`remocao_vogal_tematica` (`id`, `remover_sufixo`, `tamanho_minimo`) VALUES (3, 'o', 3);

COMMIT;

